

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
#    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server